remote_theme: just-the-docs/just-the-docs

title: wt
description: A CLI tool for managing git worktrees

# Aux links (top-right of the page)
aux_links:
  "View on GitHub":
    - "https://github.com/stabai/wt-cli"

aux_links_new_tab: true

# Footer
gh_edit_link: false

# Search
search_enabled: true

# Color scheme
color_scheme: dark
